//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvaluation.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StateEvaluation.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data.
        /// </summary>
        public static string AddDataHeader {
            get {
                return ResourceManager.GetString("AddDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad mood.
        /// </summary>
        public static string BadMoodColumnHeader {
            get {
                return ResourceManager.GetString("BadMoodColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string BirthdayHeader {
            get {
                return ResourceManager.GetString("BirthdayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string BlueValueColumnHeader {
            get {
                return ResourceManager.GetString("BlueValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string ChartColumnHeader {
            get {
                return ResourceManager.GetString("ChartColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodeHeader {
            get {
                return ResourceManager.GetString("CodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateColumnHeader {
            get {
                return ResourceManager.GetString("DateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition.
        /// </summary>
        public static string ExpeditionHeader {
            get {
                return ResourceManager.GetString("ExpeditionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string FirstnameHeader {
            get {
                return ResourceManager.GetString("FirstnameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Weaknes.
        /// </summary>
        public static string GeneralWeaknesColumnHeader {
            get {
                return ResourceManager.GetString("GeneralWeaknesColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy head.
        /// </summary>
        public static string HeavyHeadColumnHeader {
            get {
                return ResourceManager.GetString("HeavyHeadColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string LastnameHeader {
            get {
                return ResourceManager.GetString("LastnameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  1        2        3        4        5        6        7        8        9        10        11        12.
        /// </summary>
        public static string LongColorsArrayColumnHeader {
            get {
                return ResourceManager.GetString("LongColorsArrayColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make chart.
        /// </summary>
        public static string MakeChartToolTip {
            get {
                return ResourceManager.GetString("MakeChartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename.
        /// </summary>
        public static string MiddlenameHeader {
            get {
                return ResourceManager.GetString("MiddlenameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberHeader {
            get {
                return ResourceManager.GetString("NumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string PersonsTabHeader {
            get {
                return ResourceManager.GetString("PersonsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor appetite.
        /// </summary>
        public static string PoorAppetiteColumnHeader {
            get {
                return ResourceManager.GetString("PoorAppetiteColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor sleep.
        /// </summary>
        public static string PoorSleepColumnHeader {
            get {
                return ResourceManager.GetString("PoorSleepColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string PreferenceColumnHeader {
            get {
                return ResourceManager.GetString("PreferenceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string PreferenceCompareColumnHeader {
            get {
                return ResourceManager.GetString("PreferenceCompareColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string ProfessionHeader {
            get {
                return ResourceManager.GetString("ProfessionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string RedValueColumnHeader {
            get {
                return ResourceManager.GetString("RedValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    1       2       3.
        /// </summary>
        public static string ShortColorsArrayColumnHeader {
            get {
                return ResourceManager.GetString("ShortColorsArrayColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow thinking.
        /// </summary>
        public static string SlowThinkColumnHeader {
            get {
                return ResourceManager.GetString("SlowThinkColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjective Feelings.
        /// </summary>
        public static string SubjectiveFeelingsTabHeader {
            get {
                return ResourceManager.GetString("SubjectiveFeelingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string TestsTabHeader {
            get {
                return ResourceManager.GetString("TestsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string YellowValueColumnHeader {
            get {
                return ResourceManager.GetString("YellowValueColumnHeader", resourceCulture);
            }
        }
    }
}
